apiVersion: v1
kind: Service
metadata:
  name: graham-bbet
  namespace: graham-banano
spec:
  type: ClusterIP
  ports:
  - port: 11337
    targetPort: 11337
    name: api
  selector:
    app: grahambbet-server